# Web Scraper

In [1]:
from bs4 import BeautifulSoup
import requests

Require input is the URL.

In [5]:
url = 'https://www.britannica.com/topic/list-of-state-capitals-in-the-United-States-2119210'
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')
# print(soup)

Find all tables in the page. In this website, though, there's only one so it's simple.

In [6]:
soup.find_all('table')

[<table data-sortable-table="true"> <thead> <tr> <th data-col-type="text" data-sortable-type="alpha">state</th> <th data-col-type="text" data-sortable-type="alpha">capital</th> <th data-col-type="number" data-sortable-type="numeric">population of capital: census</th> <th data-col-type="number" data-sortable-type="numeric">population of capital: estimated</th> </tr> </thead> <tbody> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Alabama-state">Alabama</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Montgomery-Alabama">Montgomery</a></td> <td>(2020) 200,603</td> <td>(2021 est.) 198,665</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Alaska">Alaska</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Juneau">Juneau</a></td> <td>(2020) 32,255</td> <td>(2021 est.) 31,973</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Arizona-state">Arizona</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Phoenix-Arizona">Phoenix</a></td> <td>(2020) 1,608,139</td> <td>(2021 est.) 1,624,569</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Arkansas-state">Arkansas</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Little-Rock">Little Rock</a></td> <td>(2020) 202,591</td> <td>(2021 est.) 201,998</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/California-state">California</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Sacramento-California">Sacramento</a></td> <td>(2020) 524,943</td> <td>(2021 est.) 525,041</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Colorado-state">Colorado</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Denver">Denver</a></td> <td>(2020) 715,522</td> <td>(2021 est.) 711,463</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Connecticut">Connecticut</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Hartford-Connecticut">Hartford</a></td> <td>(2020) 121,054</td> <td>(2021 est.) 120,576</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Delaware-state">Delaware</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Dover-Delaware">Dover</a></td> <td>(2020) 39,403</td> <td>(2021 est.) 38,992</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Florida">Florida</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Tallahassee">Tallahassee</a></td> <td>(2020) 196,068</td> <td>(2021 est.) 197,102</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Georgia-state">Georgia</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Atlanta-Georgia">Atlanta</a></td> <td>(2020) 498,715</td> <td>(2021 est.) 496,461</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Hawaii-state">Hawaii</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Honolulu">Honolulu</a></td> <td>(2020) 350,964</td> <td>(2021 est.) 345,510</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Idaho">Idaho</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Boise-Idaho">Boise</a></td> <td>(2020) 235,684</td> <td>(2021 est.) 237,446</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Illinois-state">Illinois</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Springfield-Illinois">Springfield</a></td> <td>(2020) 114,394</td> <td>(2021 est.) 113,394</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Indiana-state">Indiana</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Indianapolis-Indiana">Indianapolis</a></td> <td>(2020) 887,642</td> <td>(2021 est.) 882,039</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Iowa-state">Iowa</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Des-Moines">Des Moines</a></td> <td>(2020) 214,133</td> <td>(2021 est.) 212,031</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Kansas">Kansas</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Topeka">Topeka</a></td> <td>(2020) 126,587</td> <td>(2021 est.) 125,963</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Kentucky">Kentucky</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Frankfort-Kentucky">Frankfort</a></td> <td>(2020) 28,602</td> <td>(2021 est.) 28,595</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Louisiana-state">Louisiana</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Baton-Rouge">Baton Rouge</a></td> <td>(2020) 227,470</td> <td>(2021 est.) 222,185</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Maine-state">Maine</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Augusta-Maine">Augusta</a></td> <td>(2020) 18,899</td> <td>(2021 est.) 18,968</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Maryland-state">Maryland</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Annapolis">Annapolis</a></td> <td>(2020) 40,812</td> <td>(2021 est.) 40,687</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Massachusetts">Massachusetts</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Boston">Boston</a></td> <td>(2020) 675,647</td> <td>(2021 est.) 654,776</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Michigan">Michigan</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Lansing-Michigan">Lansing</a></td> <td>(2020) 112,644</td> <td>(2021 est.) 112,684</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Minnesota">Minnesota</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Saint-Paul-Minnesota">Saint Paul</a></td> <td>(2020) 311,527</td> <td>(2021 est.) 307,193</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Mississippi-state">Mississippi</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Jackson-Mississippi">Jackson</a></td> <td>(2020) 153,701</td> <td>(2021 est.) 149,761</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Missouri-state">Missouri</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Jefferson-City">Jefferson City</a></td> <td>(2020) 43,228</td> <td>(2021 est.) 42,772</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Montana-state">Montana</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Helena-Montana">Helena</a></td> <td>(2020) 32,091</td> <td>(2021 est.) 33,120</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Nebraska-state">Nebraska</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Lincoln-Nebraska">Lincoln</a></td> <td>(2020) 291,082</td> <td>(2021 est.) 292,657</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Nevada-state">Nevada</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Carson-City">Carson City</a></td> <td>(2020) 58,639</td> <td>(2021 est.) 58,993</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/New-Hampshire-state">New Hampshire</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Concord-New-Hampshire">Concord</a></td> <td>(2020) 43,976</td> <td>(2021 est.) 44,006</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/New-Jersey">New Jersey</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Trenton-New-Jersey">Trenton</a></td> <td>(2020) 90,871</td> <td>(2021 est.) 90,457</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/New-Mexico">New Mexico</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Santa-Fe-New-Mexico">Santa Fe</a></td> <td>(2020) 87,505</td> <td>(2021 est.) 88,193</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/New-York-state">New York</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Albany-New-York">Albany</a></td> <td>(2020) 99,224</td> <td>(2021 est.) 98,617</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/North-Carolina-state">North Carolina</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Raleigh-North-Carolina">Raleigh</a></td> <td>(2020) 467,665</td> <td>(2021 est.) 469,124</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/North-Dakota">North Dakota</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Bismarck-North-Dakota">Bismarck</a></td> <td>(2020) 73,622</td> <td>(2021 est.) 74,138</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Ohio-state">Ohio</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Columbus-Ohio">Columbus</a></td> <td>(2020) 905,748</td> <td>(2021 est.) 906,528</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Oklahoma-state">Oklahoma</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Oklahoma-City">Oklahoma City</a></td> <td>(2020) 681,054</td> <td>(2021 est.) 687,725</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Oregon-state">Oregon</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Salem-Oregon">Salem</a></td> <td>(2020) 175,535</td> <td>(2021 est.) 177,723</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Pennsylvania-state">Pennsylvania</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Harrisburg-Pennsylvania">Harrisburg</a></td> <td>(2020) 50,099</td> <td>(2021 est.) 50,135</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Rhode-Island-state">Rhode Island</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Providence-Rhode-Island">Providence</a></td> <td>(2020) 190,934</td> <td>(2021 est.) 189,692</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/South-Carolina">South Carolina</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Columbia-South-Carolina">Columbia</a></td> <td>(2020) 136,632</td> <td>(2021 est.) 137,541</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/South-Dakota">South Dakota</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Pierre-South-Dakota">Pierre</a></td> <td>(2020) 14,091</td> <td>(2021 est.) 14,000</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Tennessee">Tennessee</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Nashville-Tennessee">Nashville</a></td> <td>(2020) 689,447</td> <td>(2021 est.) 678,851</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Texas-state">Texas</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Austin-Texas">Austin</a></td> <td>(2020) 961,855</td> <td>(2021 est.) 964,177</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Utah">Utah</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Salt-Lake-City">Salt Lake City</a></td> <td>(2020) 199,723</td> <td>(2021 est.) 200,478</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Vermont">Vermont</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Montpelier-Vermont">Montpelier</a></td> <td>(2020) 8,074</td> <td>(2021 est.) 8,002</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Virginia-state">Virginia</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Richmond-Virginia">Richmond</a></td> <td>(2020) 226,610</td> <td>(2021 est.) 226,604</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Washington-state">Washington</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Olympia-Washington">Olympia</a></td> <td>(2020) 55,605</td> <td>(2021 est.) 55,919</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/West-Virginia">West Virginia</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Charleston-West-Virginia">Charleston</a></td> <td>(2020) 48,864</td> <td>(2021 est.) 48,018</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Wisconsin">Wisconsin</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Madison-Wisconsin">Madison</a></td> <td>(2020) 269,840</td> <td>(2021 est.) 269,196</td> </tr> <tr> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Wyoming-state">Wyoming</a></td> <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Cheyenne-Wyoming">Cheyenne</a></td> <td>(2020) 65,132</td> <td>(2021 est.) 65,051</td> </tr> </tbody> </table>]

Let's first get just the title of the table.

*Note: `<th>` tag defines a header cell in an HTML table*

In [7]:
titles = soup.find_all('th')
titles

[<th data-col-type="text" data-sortable-type="alpha">state</th>,
 <th data-col-type="text" data-sortable-type="alpha">capital</th>,
 <th data-col-type="number" data-sortable-type="numeric">population of capital: census</th>,
 <th data-col-type="number" data-sortable-type="numeric">population of capital: estimated</th>]

Since we do not need the tags, let's clean up the data.

In [8]:
titles_list = [title.text for title in titles]
titles_list

['state',
 'capital',
 'population of capital: census',
 'population of capital: estimated']

If the output still contains newline and other symbols that are not needed, you can further clean the data using, for example, ```.strip()```

Next, create a dataframe

In [9]:
import pandas as pd

df = pd.DataFrame(columns = titles_list)
df

Empty DataFrame
Columns: [state, capital, population of capital: census, population of capital: estimated]
Index: []

Let's scrape the remaining data and fill this table!

In [10]:
rows = soup.find_all('tr')
len(rows)

51

The data of our interest are within the scope of **td** tags.

*Note: `<td>` tag defines a standard data cell in an HTML table.*

In [11]:
# -- Long version --
# row_data = []
# for row in rows:
#   row_data.append(row.find_all('td'))

# -- Short version --
row_data = [row.find_all('td') for row in rows]
row_data

[[],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Alabama-state">Alabama</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Montgomery-Alabama">Montgomery</a></td>,
  <td>(2020) 200,603</td>,
  <td>(2021 est.) 198,665</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Alaska">Alaska</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Juneau">Juneau</a></td>,
  <td>(2020) 32,255</td>,
  <td>(2021 est.) 31,973</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Arizona-state">Arizona</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Phoenix-Arizona">Phoenix</a></td>,
  <td>(2020) 1,608,139</td>,
  <td>(2021 est.) 1,624,569</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Arkansas-state">Arkansas</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Little-Rock">Little Rock</a></td>,
  <td>(2020) 202,591</td>,
  <td>(2021 est.) 201,998</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/California-state">California</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Sacramento-California">Sacramento</a></td>,
  <td>(2020) 524,943</td>,
  <td>(2021 est.) 525,041</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Colorado-state">Colorado</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Denver">Denver</a></td>,
  <td>(2020) 715,522</td>,
  <td>(2021 est.) 711,463</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Connecticut">Connecticut</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Hartford-Connecticut">Hartford</a></td>,
  <td>(2020) 121,054</td>,
  <td>(2021 est.) 120,576</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Delaware-state">Delaware</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Dover-Delaware">Dover</a></td>,
  <td>(2020) 39,403</td>,
  <td>(2021 est.) 38,992</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Florida">Florida</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Tallahassee">Tallahassee</a></td>,
  <td>(2020) 196,068</td>,
  <td>(2021 est.) 197,102</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Georgia-state">Georgia</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Atlanta-Georgia">Atlanta</a></td>,
  <td>(2020) 498,715</td>,
  <td>(2021 est.) 496,461</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Hawaii-state">Hawaii</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Honolulu">Honolulu</a></td>,
  <td>(2020) 350,964</td>,
  <td>(2021 est.) 345,510</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Idaho">Idaho</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Boise-Idaho">Boise</a></td>,
  <td>(2020) 235,684</td>,
  <td>(2021 est.) 237,446</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Illinois-state">Illinois</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Springfield-Illinois">Springfield</a></td>,
  <td>(2020) 114,394</td>,
  <td>(2021 est.) 113,394</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Indiana-state">Indiana</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Indianapolis-Indiana">Indianapolis</a></td>,
  <td>(2020) 887,642</td>,
  <td>(2021 est.) 882,039</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Iowa-state">Iowa</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Des-Moines">Des Moines</a></td>,
  <td>(2020) 214,133</td>,
  <td>(2021 est.) 212,031</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Kansas">Kansas</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Topeka">Topeka</a></td>,
  <td>(2020) 126,587</td>,
  <td>(2021 est.) 125,963</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Kentucky">Kentucky</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Frankfort-Kentucky">Frankfort</a></td>,
  <td>(2020) 28,602</td>,
  <td>(2021 est.) 28,595</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Louisiana-state">Louisiana</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Baton-Rouge">Baton Rouge</a></td>,
  <td>(2020) 227,470</td>,
  <td>(2021 est.) 222,185</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Maine-state">Maine</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Augusta-Maine">Augusta</a></td>,
  <td>(2020) 18,899</td>,
  <td>(2021 est.) 18,968</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Maryland-state">Maryland</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Annapolis">Annapolis</a></td>,
  <td>(2020) 40,812</td>,
  <td>(2021 est.) 40,687</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Massachusetts">Massachusetts</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Boston">Boston</a></td>,
  <td>(2020) 675,647</td>,
  <td>(2021 est.) 654,776</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Michigan">Michigan</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Lansing-Michigan">Lansing</a></td>,
  <td>(2020) 112,644</td>,
  <td>(2021 est.) 112,684</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Minnesota">Minnesota</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Saint-Paul-Minnesota">Saint Paul</a></td>,
  <td>(2020) 311,527</td>,
  <td>(2021 est.) 307,193</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Mississippi-state">Mississippi</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Jackson-Mississippi">Jackson</a></td>,
  <td>(2020) 153,701</td>,
  <td>(2021 est.) 149,761</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Missouri-state">Missouri</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Jefferson-City">Jefferson City</a></td>,
  <td>(2020) 43,228</td>,
  <td>(2021 est.) 42,772</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Montana-state">Montana</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Helena-Montana">Helena</a></td>,
  <td>(2020) 32,091</td>,
  <td>(2021 est.) 33,120</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Nebraska-state">Nebraska</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Lincoln-Nebraska">Lincoln</a></td>,
  <td>(2020) 291,082</td>,
  <td>(2021 est.) 292,657</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Nevada-state">Nevada</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Carson-City">Carson City</a></td>,
  <td>(2020) 58,639</td>,
  <td>(2021 est.) 58,993</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/New-Hampshire-state">New Hampshire</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Concord-New-Hampshire">Concord</a></td>,
  <td>(2020) 43,976</td>,
  <td>(2021 est.) 44,006</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/New-Jersey">New Jersey</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Trenton-New-Jersey">Trenton</a></td>,
  <td>(2020) 90,871</td>,
  <td>(2021 est.) 90,457</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/New-Mexico">New Mexico</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Santa-Fe-New-Mexico">Santa Fe</a></td>,
  <td>(2020) 87,505</td>,
  <td>(2021 est.) 88,193</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/New-York-state">New York</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Albany-New-York">Albany</a></td>,
  <td>(2020) 99,224</td>,
  <td>(2021 est.) 98,617</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/North-Carolina-state">North Carolina</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Raleigh-North-Carolina">Raleigh</a></td>,
  <td>(2020) 467,665</td>,
  <td>(2021 est.) 469,124</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/North-Dakota">North Dakota</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Bismarck-North-Dakota">Bismarck</a></td>,
  <td>(2020) 73,622</td>,
  <td>(2021 est.) 74,138</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Ohio-state">Ohio</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Columbus-Ohio">Columbus</a></td>,
  <td>(2020) 905,748</td>,
  <td>(2021 est.) 906,528</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Oklahoma-state">Oklahoma</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Oklahoma-City">Oklahoma City</a></td>,
  <td>(2020) 681,054</td>,
  <td>(2021 est.) 687,725</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Oregon-state">Oregon</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Salem-Oregon">Salem</a></td>,
  <td>(2020) 175,535</td>,
  <td>(2021 est.) 177,723</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Pennsylvania-state">Pennsylvania</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Harrisburg-Pennsylvania">Harrisburg</a></td>,
  <td>(2020) 50,099</td>,
  <td>(2021 est.) 50,135</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Rhode-Island-state">Rhode Island</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Providence-Rhode-Island">Providence</a></td>,
  <td>(2020) 190,934</td>,
  <td>(2021 est.) 189,692</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/South-Carolina">South Carolina</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Columbia-South-Carolina">Columbia</a></td>,
  <td>(2020) 136,632</td>,
  <td>(2021 est.) 137,541</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/South-Dakota">South Dakota</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Pierre-South-Dakota">Pierre</a></td>,
  <td>(2020) 14,091</td>,
  <td>(2021 est.) 14,000</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Tennessee">Tennessee</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Nashville-Tennessee">Nashville</a></td>,
  <td>(2020) 689,447</td>,
  <td>(2021 est.) 678,851</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Texas-state">Texas</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Austin-Texas">Austin</a></td>,
  <td>(2020) 961,855</td>,
  <td>(2021 est.) 964,177</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Utah">Utah</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Salt-Lake-City">Salt Lake City</a></td>,
  <td>(2020) 199,723</td>,
  <td>(2021 est.) 200,478</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Vermont">Vermont</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Montpelier-Vermont">Montpelier</a></td>,
  <td>(2020) 8,074</td>,
  <td>(2021 est.) 8,002</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Virginia-state">Virginia</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Richmond-Virginia">Richmond</a></td>,
  <td>(2020) 226,610</td>,
  <td>(2021 est.) 226,604</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Washington-state">Washington</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Olympia-Washington">Olympia</a></td>,
  <td>(2020) 55,605</td>,
  <td>(2021 est.) 55,919</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/West-Virginia">West Virginia</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Charleston-West-Virginia">Charleston</a></td>,
  <td>(2020) 48,864</td>,
  <td>(2021 est.) 48,018</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Wisconsin">Wisconsin</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Madison-Wisconsin">Madison</a></td>,
  <td>(2020) 269,840</td>,
  <td>(2021 est.) 269,196</td>],
 [<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Wyoming-state">Wyoming</a></td>,
  <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Cheyenne-Wyoming">Cheyenne</a></td>,
  <td>(2020) 65,132</td>,
  <td>(2021 est.) 65,051</td>]]

The first row collected has no value, thus an empty list.

In [12]:
row_data[0]

[]

Turns out the first row is actually here

In [13]:
row_data[1]

[<td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Alabama-state">Alabama</a></td>,
 <td><a class="md-crosslink sortable" data-show-preview="true" href="https://www.britannica.com/place/Montgomery-Alabama">Montgomery</a></td>,
 <td>(2020) 200,603</td>,
 <td>(2021 est.) 198,665</td>]

However, we only want the text portion.

In [14]:
print(row_data[1][0].text)
print(row_data[1][1].text)
print(row_data[1][2].text)
print(row_data[1][3].text)

Alabama
Montgomery
(2020) 200,603
(2021 est.) 198,665

Therefore, more cleaning is necessary.

Add the remaining rows to the dataframe.

But does this code work?

In [19]:
df.head()

Empty DataFrame
Columns: [state, capital, population of capital: census, population of capital: estimated]
Index: []

In [18]:
for each_row_data in row_data:
  state=[]
  for each_row_data_elem in each_row_data:
    state.append(each_row_data_elem.text)

  length = len(df)
  df.loc[length] = state

ValueError: cannot set a row with mismatched columns

In [16]:
df

Empty DataFrame
Columns: [state, capital, population of capital: census, population of capital: estimated]
Index: []

TODO:

- Scrape other table from wikipedia
- Generate a new table/tables using dataframe
- Feel free to use other html tags
- Clean & preprocess

---

Other websites (for instance)
- https://www.timesjobs.com/
- https://www.tripadvisor.com/